### ISSUE TITLE
Highlight the modifier instead of the entire object in diff window

### ISSUE THREAD

**Issue by anchouls** [JetBrains-Research/RefactorInsight#104]
In classes `AddMethodModifierRefactoring, RemoveMethodModifierRefactoring, AddAttributeModifierRefactoring, AddVariableModifierRefactoring, ...` modifier has String type, so it doesn't have Location Info.

**Comment by tsantalis** [comment]
Class `UMLModifier` was introduced that provides `LocationInfo`

All AddXXXXModifier refactorings have a method `UMLModifier getAddedModifier()`

All RemoveXXXXModifier refactorings have a method `UMLModifier getRemovedModifier()`

All ChangeXXXXAccessModifier refactorings have two methods `UMLModifier getOldModifier()` and `UMLModifier getNewModifier()`
**Note** These methods will return `null` if the modifier is `package-private`, because for `package-private` access no keyword is used.
