### ISSUE TITLE
refactorings.xml is not part of .idea/.gitignore

### ISSUE THREAD

**Issue by mikhail-putilov** [JetBrains-Research/RefactorInsight#112]
Hi,

Today I realized that I am committing a file with my local filesystem paths into a common repo because `.idea/.gitignore` does not include `refactorings.xml` as ignorable file.

![image](https://user-images.githubusercontent.com/699726/220683959-e4678219-ede0-49d4-a262-2fe06e2517d2.png)
![image](https://user-images.githubusercontent.com/699726/220684254-cc05979c-e16a-4657-ac64-00b71ad83e5b.png)

**Comment by onewhl** [comment]
@mikhail-putilov thank you very much! We will try to fix it and then I will get back to you.

**Comment by dimonchik0036** [comment]
Probably the right solution here is not to add this file to gitignore, because it still will annoy users.
I think you shouldn't introduce a new storage, because, as far as I understand, the file is not supposed to be shared with team members.
So, either at least the storage should be marked as `RoamingType#DISABLED`, or `StoragePathMacros#WORKSPACE_FILE` or `com.intellij.openapi.components.StoragePathMacros#CACHE_FILE` should be used instead of the custom storage.

**Comment by onewhl** [comment]
@dimonchik0036 thank you, I've fixed it as you suggested! 
@mikhail-putilov fix will come in the **next** plugin release. After updating, please, just remove this file "refactorings.xml", it will not be needed.
