### ISSUE TITLE
Make refactoring names more intuitive 

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/RefactorInsight#121]
Come up with more intuitive names for refactorings, especially for ones IDE doesn't have an action for.
I suggest rephrasing these refactoring names: 
`Replace Pipeline with Loop`
`Replace Loop with Pipeline`
`Localize Parameter`
`Parameterize Variable`
`Encapsulate Attribute`
`Parameterize Attribute`
`Localize Parameter`
`Collapse Hierarchy`

**Comment by tsantalis** [comment]
@onewhl 
Pipeline is not used for any kind of method call chain (e.g., builder chain), but specifically for the Java Stream API.
`stream()`, `forEach()`, `filter()`, `collect()`, `map()`, etc.

So, in the context of Java and Kotlin, this refactoring is replace Loop with Stream API

![Screenshot from 2023-03-15 14-12-05](https://user-images.githubusercontent.com/1483516/225404115-13dc8a87-4196-4492-a546-6910cac06f57.png)

For the others, your suggestions are fine.

`Localize Parameter` is when a method parameter becomes a local variable.
`Parameter Variable` is when a local variable becomes a method parameter.
`Parameterize Attribute` is when a parameter is introduced in the method instead of referencing a field (the references to a field are replaced with references to a local method parameter).

**Comment by onewhl** [comment]
@tsantalis thank you!

**Comment by onewhl** [comment]
Also, let's rename "Mining commit <commit hash>" to  "Detect refactorings in <commit hash>" on progress indicator

**Comment by onewhl** [comment]
@tsantalis could you please help me to understand why RefactoringMiner concluded that there was a Parameterize Variable refactoring in the following [commit](https://github.com/JetBrains/Arend/commit/2dee927f69c9a8ebcf150380a6625174b5b5bbd3#diff-bc324084e078753f78a9d93979cc2d818159d40e22dbac91b630c5606ebd74fdR78)? We renamed refactoring type corresponding to your comments, we plan to release this version next days.

Maybe we highlight the wrong lines?
<img width="703" alt="Screen Shot 2023-03-20 at 12 29 47 PM" src="https://user-images.githubusercontent.com/10652414/226326966-1bfda12f-aa5c-41af-8772-819be72efba7.png">
<img width="1702" alt="Screen Shot 2023-03-20 at 12 30 16 PM" src="https://user-images.githubusercontent.com/10652414/226327053-ba4283bb-1831-4a0e-a543-8f86992da4de.png">

**Comment by tsantalis** [comment]
@onewhl 
`doSave(Definition def)` is an extracted method that contains part of the `if` conditions

`if (typechecked != null && typechecked.status().withoutErrors() && !(typechecked instanceof Constructor || typechecked instanceof ClassField)) {`
matched with
`return def == null || def.status().withoutErrors()` ... in the extracted method.

In this Extract Method Refactoring the local variable `typechecked` is passed as parameter `def` and its name changes.

Because of that reason RefactoringMiner reports a Parameterize Variable for the Extracted Method (not the original one).

`RenameVariableRefactoring` has a property called `insideExtractedOrInlinedMethod`
If it has a `true` value, I would suggest to skip the visualization or show it in a different way.
Right now the visualization is confusing. I agree with you.

![Screenshot from 2023-03-21 14-32-43](https://user-images.githubusercontent.com/1483516/226708001-4134daeb-a4f6-4790-ac0a-d59befa44e90.png)

**Comment by onewhl** [comment]
@tsantalis thanks for clarifications!
