### ISSUE TITLE
Visualization as a list of refactoring changes in code diffs

### ISSUE THREAD

**Issue by anchouls** [JetBrains-Research/RefactorInsight#97]
Gutter helps to mark refactoring changes in code diffs. Changes must be presented as a list if there are several of them on one line.

**Comment by anchouls** [comment]
Visualization can be represented like this:
![image](https://user-images.githubusercontent.com/57748412/214230313-e7c115f9-cb5a-4bae-954f-f060cf8a86e2.png)

At the moment I visualized like this:
![image](https://user-images.githubusercontent.com/57748412/214230277-449f4a07-c4c5-4525-b356-04ac9b53855e.png)

Diffs shows when pressed. Perhaps a more detailed description can be shown on hover, if it is possible to define

**Comment by onewhl** [comment]
@anchouls, cool! I have a couple of suggestions✌️

- Is it possible to make the size of the panel dependent on the text? I mean now the panel is quite wide in all cases, but it could be smaller/bigger depending on the count of characters in the refactoring description. 

- Also, the arrow on the right side of the panel makes me think that something will appear on the right side of it, but it opens an editor with diff. Maybe we can use another icon instead of arrow?

**Comment by anchouls** [comment]
I think this visualization is generally good:

<img width="200" alt="Снимок экрана 2023-01-27 в 22 17 18" src="https://user-images.githubusercontent.com/57748412/215202616-fd57d2f3-9ca7-4cd7-b583-6b0fe8268b54.png">

**Comment by onewhl** [comment]
@anchouls looks good, thank you!
Maybe we can use icons for method, class, variable like we do it [here](https://github.com/JetBrains-Research/RefactorInsight/blob/master/assets/img/refactorinsight_pull_requests.png)?

**Comment by anchouls** [comment]
Do you mean like in the first or second image?
![photo_2023-02-03_02-01-47](https://user-images.githubusercontent.com/57748412/216486083-47b75f87-7ed3-4c22-a073-19fcb8d4c9bf.jpg)
![photo_2023-02-03_02-02-04](https://user-images.githubusercontent.com/57748412/216486099-63af0278-d57c-4889-be47-18e1b1a3df78.jpg)

**Comment by onewhl** [comment]
@anchouls , second image
